### ISSUE TITLE
Get full price back in `continue building`-mode

### ISSUE THREAD

**Issue by tolik518** [evanbowman/skyland-beta#10]
After one wins a fight you get prompted with `sky map` and `continue building`.

In the `continue building`-mode there is no strategical benefit in selling new build blocks. 
It would be expected if to get the full price back for blocks you build in the `continue building`-mode.

I can understand that you won't get the full price back for the blocks you build in a battle - but I think you should get the full price
back on block that you build afterwards.

This would open more room for experimentation without getting penalized.

**Comment by evanbowman** [comment]
Great idea! I added the continue building option based on a request from other players, and never really developed it much. I've changed the code and will create a release soon!

**Comment by evanbowman** [comment]
In the latest release, you now get the full price back and can also enter the block rearrangement mode for free after selecting continue building.
https://github.com/evanbowman/skyland-beta/releases/tag/2023.3.25.0
