### ISSUE TITLE
Bug - transporter

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#101]
**Describe the bug**
Sometimes the crewmember will leave the transporter in the same frame of being transported, the crewmember will stay in the castle but the transporter will restart the cooldown

**To Reproduce**
Move the crewmember at the same time of transportation (extremely finicky and 99.9% of the time will not work)

**Expected behavior**
Do not restart the cooldown

**Additional context**
Issue was encountered in the nemesis challenge.

**Comment by evanbowman** [comment]
Can you help me understand the steps to reproduce better? To move the crewmember at the same time as activating the transporter, do you have the game paused?

**Comment by Doronimmo** [comment]
> I don't know if this is the same issue, but when you have a radar, and enter the destination selection, if the crewmember walks out of the transporter, then I am able to reproduce the bug in that case.

Could be

**Comment by Doronimmo** [comment]
> Can you help me understand the steps to reproduce better? To move the crewmember at the same time as activating the transporter, do you have the game paused?

No, but I find the rewind helpful

**Comment by evanbowman** [comment]
> > I don't know if this is the same issue, but when you have a radar, and enter the destination selection, if the crewmember walks out of the transporter, then I am able to reproduce the bug in that case.
> 
> Could be

I'm not sure if this is the same issue, but I'll fix this one and push the changes

**Comment by Doronimmo** [comment]
> > > I don't know if this is the same issue, but when you have a radar, and enter the destination selection, if the crewmember walks out of the transporter, then I am able to reproduce the bug in that case.
> > 
> > 
> > Could be
> 
> I'm not sure if this is the same issue, but I'll fix this one and push the changes

Haven't encountered this issue since, closing.
