### ISSUE TITLE
Enhancement - 0 hp replicants

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#107]
it is possible to create dead replicants, and replicants with non integer hp (rounded to 0 but still alive)

**Comment by evanbowman** [comment]
Ah, I never thought about that. I'll make sure that the minimum health when creating a replicant is 1.

**Comment by evanbowman** [comment]
7290886ab20da54c70f293c3c9c8b801986d10e3

Now they have 1hp at a minimum, this also fixes replicant's max health statistic upon loading save files.
