### ISSUE TITLE
ENHANCEMENT -  a warning before going to a dead end if you don't have a radar

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#112]
Sometimes, it is possible to get stuck without a radar, a warning before going to a place with no close tiles could help make navigation less frustrating

**Comment by evanbowman** [comment]
Yeah, I've been thinking about how to show hints on the map better. When you're moving to a new map location and hover over top of it, the game shades the areas that are reachable in one or two moves.
![Skyland-196](https://github.com/user-attachments/assets/bcfc9ea1-10ec-4aeb-9348-44d7c6286380)

But it's still sometimes difficult to plan further ahead than a couple of moves, depending on the arrangement of the world map. I'll think about how to show this better.

Some things that I've thought about:
1) An option to plot a course through the map, and the game visualizes the movement of the storm as you plot future destinations
2) More levels of shading for the reachability hints in the screenshot above. But I'm running close to the sprite limit when drawing more than two levels of shading.

**Comment by evanbowman** [comment]
I'm also thinking of making the path drawing option accessible with a new icon at the bottom of the screen, so that people know that it exists as an option.

**Comment by Doronimmo** [comment]
> I'm also thinking of making the path drawing option accessible with a new icon at the bottom of the screen, so that people know that it exists as an option.

Maybe you could add it in the tips and tricks section

**Comment by evanbowman** [comment]
> > I'm also thinking of making the path drawing option accessible with a new icon at the bottom of the screen, so that people know that it exists as an option.
> 
> Maybe you could add it in the tips and tricks section

![ezgif-7-5a44294aa4](https://github.com/user-attachments/assets/8d6a3d44-5718-45e2-b522-a6826856b075)
It's starting to look kind of decent

**Comment by Doronimmo** [comment]
> > > I'm also thinking of making the path drawing option accessible with a new icon at the bottom of the screen, so that people know that it exists as an option.
> > 
> > 
> > Maybe you could add it in the tips and tricks section
> 
> [ ![ezgif-7-5a44294aa4](https://private-user-images.githubusercontent.com/11904320/391189169-8d6a3d44-5718-45e2-b522-a6826856b075.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MTU3NjAsIm5iZiI6MTczMjkxNTQ2MCwicGF0aCI6Ii8xMTkwNDMyMC8zOTExODkxNjktOGQ2YTNkNDQtNTcxOC00NWUyLWI1MjItYTY4MjY4NTZiMDc1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDIxMjQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MDM3YjM2YzQxZGQ0ZmRlZjcwNmY4MzViZWRmZGQ4OTFkMjkzYmI2M2UwNWU3Y2Y2YTY0YTQ2OGI4YTk0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yxWKyZdH502kbf1WSyrxFZlGPmlLBP68C8N1pBYbeR0) ](https://private-user-images.githubusercontent.com/11904320/391189169-8d6a3d44-5718-45e2-b522-a6826856b075.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MTU3NjAsIm5iZiI6MTczMjkxNTQ2MCwicGF0aCI6Ii8xMTkwNDMyMC8zOTExODkxNjktOGQ2YTNkNDQtNTcxOC00NWUyLWI1MjItYTY4MjY4NTZiMDc1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDIxMjQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MDM3YjM2YzQxZGQ0ZmRlZjcwNmY4MzViZWRmZGQ4OTFkMjkzYmI2M2UwNWU3Y2Y2YTY0YTQ2OGI4YTk0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yxWKyZdH502kbf1WSyrxFZlGPmlLBP68C8N1pBYbeR0) [ ](https://private-user-images.githubusercontent.com/11904320/391189169-8d6a3d44-5718-45e2-b522-a6826856b075.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MTU3NjAsIm5iZiI6MTczMjkxNTQ2MCwicGF0aCI6Ii8xMTkwNDMyMC8zOTExODkxNjktOGQ2YTNkNDQtNTcxOC00NWUyLWI1MjItYTY4MjY4NTZiMDc1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDIxMjQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MDM3YjM2YzQxZGQ0ZmRlZjcwNmY4MzViZWRmZGQ4OTFkMjkzYmI2M2UwNWU3Y2Y2YTY0YTQ2OGI4YTk0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yxWKyZdH502kbf1WSyrxFZlGPmlLBP68C8N1pBYbeR0) It's starting to look kind of decent

Kinda looks like a conspiracy board :)

**Comment by evanbowman** [comment]
> > > > I'm also thinking of making the path drawing option accessible with a new icon at the bottom of the screen, so that people know that it exists as an option.
> > > 
> > > 
> > > Maybe you could add it in the tips and tricks section
> > 
> > 
> > [ ![ezgif-7-5a44294aa4](https://private-user-images.githubusercontent.com/11904320/391189169-8d6a3d44-5718-45e2-b522-a6826856b075.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MTU3NjAsIm5iZiI6MTczMjkxNTQ2MCwicGF0aCI6Ii8xMTkwNDMyMC8zOTExODkxNjktOGQ2YTNkNDQtNTcxOC00NWUyLWI1MjItYTY4MjY4NTZiMDc1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDIxMjQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MDM3YjM2YzQxZGQ0ZmRlZjcwNmY4MzViZWRmZGQ4OTFkMjkzYmI2M2UwNWU3Y2Y2YTY0YTQ2OGI4YTk0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yxWKyZdH502kbf1WSyrxFZlGPmlLBP68C8N1pBYbeR0) ](https://private-user-images.githubusercontent.com/11904320/391189169-8d6a3d44-5718-45e2-b522-a6826856b075.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MTU3NjAsIm5iZiI6MTczMjkxNTQ2MCwicGF0aCI6Ii8xMTkwNDMyMC8zOTExODkxNjktOGQ2YTNkNDQtNTcxOC00NWUyLWI1MjItYTY4MjY4NTZiMDc1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDIxMjQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MDM3YjM2YzQxZGQ0ZmRlZjcwNmY4MzViZWRmZGQ4OTFkMjkzYmI2M2UwNWU3Y2Y2YTY0YTQ2OGI4YTk0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yxWKyZdH502kbf1WSyrxFZlGPmlLBP68C8N1pBYbeR0)
> >       
> >         [
> >           
> >             ![ezgif-7-5a44294aa4](https://private-user-images.githubusercontent.com/11904320/391189169-8d6a3d44-5718-45e2-b522-a6826856b075.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MTU3NjAsIm5iZiI6MTczMjkxNTQ2MCwicGF0aCI6Ii8xMTkwNDMyMC8zOTExODkxNjktOGQ2YTNkNDQtNTcxOC00NWUyLWI1MjItYTY4MjY4NTZiMDc1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDIxMjQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MDM3YjM2YzQxZGQ0ZmRlZjcwNmY4MzViZWRmZGQ4OTFkMjkzYmI2M2UwNWU3Y2Y2YTY0YTQ2OGI4YTk0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yxWKyZdH502kbf1WSyrxFZlGPmlLBP68C8N1pBYbeR0)
> >           
> >         ](https://private-user-images.githubusercontent.com/11904320/391189169-8d6a3d44-5718-45e2-b522-a6826856b075.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MTU3NjAsIm5iZiI6MTczMjkxNTQ2MCwicGF0aCI6Ii8xMTkwNDMyMC8zOTExODkxNjktOGQ2YTNkNDQtNTcxOC00NWUyLWI1MjItYTY4MjY4NTZiMDc1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDIxMjQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MDM3YjM2YzQxZGQ0ZmRlZjcwNmY4MzViZWRmZGQ4OTFkMjkzYmI2M2UwNWU3Y2Y2YTY0YTQ2OGI4YTk0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yxWKyZdH502kbf1WSyrxFZlGPmlLBP68C8N1pBYbeR0)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/11904320/391189169-8d6a3d44-5718-45e2-b522-a6826856b075.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MTU3NjAsIm5iZiI6MTczMjkxNTQ2MCwicGF0aCI6Ii8xMTkwNDMyMC8zOTExODkxNjktOGQ2YTNkNDQtNTcxOC00NWUyLWI1MjItYTY4MjY4NTZiMDc1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDIxMjQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MDM3YjM2YzQxZGQ0ZmRlZjcwNmY4MzViZWRmZGQ4OTFkMjkzYmI2M2UwNWU3Y2Y2YTY0YTQ2OGI4YTk0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yxWKyZdH502kbf1WSyrxFZlGPmlLBP68C8N1pBYbeR0)
> >         
> >        [ ](https://private-user-images.githubusercontent.com/11904320/391189169-8d6a3d44-5718-45e2-b522-a6826856b075.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MTU3NjAsIm5iZiI6MTczMjkxNTQ2MCwicGF0aCI6Ii8xMTkwNDMyMC8zOTExODkxNjktOGQ2YTNkNDQtNTcxOC00NWUyLWI1MjItYTY4MjY4NTZiMDc1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDIxMjQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MDM3YjM2YzQxZGQ0ZmRlZjcwNmY4MzViZWRmZGQ4OTFkMjkzYmI2M2UwNWU3Y2Y2YTY0YTQ2OGI4YTk0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yxWKyZdH502kbf1WSyrxFZlGPmlLBP68C8N1pBYbeR0) It's starting to look kind of decent
> 
> Kinda looks like a conspiracy board :)

You should have seen the version where I was putting those red pins on every node in the path. I removed it because it cluttered the screen too much and was hard to understand

**Comment by Doronimmo** [comment]
![20241130_104404](https://github.com/user-attachments/assets/a71b2159-a1f9-4484-a217-a8c1783250fd)
Graphical glitch encountered on release version.
Also: is there a way to plot a course with a radar range?

**Comment by Doronimmo** [comment]
![20241130_104800](https://github.com/user-attachments/assets/2aa9c78e-6d3a-49e0-b746-72fc700b7762)
Looks like the course is cut by the storm marker

**Comment by evanbowman** [comment]
![Skyland-208](https://github.com/user-attachments/assets/4c475eba-647a-45ec-9569-ae204dcf7bdd)
The cropping is definitely a problem, I'm looking into it. The storm marker overlapping the path, on the other hand, is expected, because it's on a higher tile layer, I'll have to try to move it to one of the background layers perhaps

**Comment by evanbowman** [comment]
> Also: is there a way to plot a course with a radar range?

Unfortunately, at the moment, the only way is to already have a radar.

**Comment by Doronimmo** [comment]
> > Also: is there a way to plot a course with a radar range?
> 
> Unfortunately, at the moment, the only way is to already have a radar.

Looks like the radar range is default even if you don't have a radar

**Comment by evanbowman** [comment]
> > > Also: is there a way to plot a course with a radar range?
> > 
> > 
> > Unfortunately, at the moment, the only way is to already have a radar.
> 
> Looks like the radar range is default even if you don't have a radar

I haven't seen this happen myself

**Comment by evanbowman** [comment]
> In zone 4, when finishing to plot a course, the game will not count it as finished since there is not exit

Technically you can finish drawing at any time by pressing select, I should make this more obvious.

**Comment by Doronimmo** [comment]
> > In zone 4, when finishing to plot a course, the game will not count it as finished since there is not exit
> 
> Technically you can finish drawing at any time by pressing select, I should make this more obvious.

If you are not careful the game will set the course as unreachable before you could save it

**Comment by Doronimmo** [comment]
> > > > Also: is there a way to plot a course with a radar range?
> > > 
> > > 
> > > Unfortunately, at the moment, the only way is to already have a radar.
> > 
> > 
> > Looks like the radar range is default even if you don't have a radar
> 
> I haven't seen this happen myself

There seems to be a big where if there is no valid path forward the game will sometimes extend the range

**Comment by Doronimmo** [comment]
Looks like the path is not saved when quitting

**Comment by evanbowman** [comment]
> Looks like the path is not saved when quitting

I can add it to the save data

**Comment by Doronimmo** [comment]
Closing issue to clean things up
