### ISSUE TITLE
ENHANCEMENT - choose ladder/cargo-bay/etc placement

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#113]
**Is your feature request related to a problem? Please describe.**
Currently, some events allow the player to choose where to place blocks they receive, while others do not, which creates confusion. Additionally, the auto-placement bot is not very efficient.

**Describe the desired behavior**
Ensure consistency by always allowing or disallowing the player to place items manually, depending on the context.

**Comment by Doronimmo** [comment]
Progress update:
You can now place cargo bays and amplifiers! (thanks!)

**Comment by evanbowman** [comment]
I focused on fixing those three first, because the events where it drops a block into a random spot happens every time. The other cases where the game drops a ladder into a random spot where there's no room for new crew members happens less frequently, but I'm working on fixing those too.

**Comment by Doronimmo** [comment]
I think this issue is ready to be closed
