### ISSUE TITLE
Bug - 3 shop

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#114]
**Describe the bug**
![20241130_125949](https://github.com/user-attachments/assets/438e98fe-1530-4378-9793-031cfa255ea1)
Looks like the shop was exploded by the  cannon projectile from previous encounter

Maybe you could keep the projectiles moving after victory, so by the next encounter they will be gone

**Comment by Doronimmo** [comment]
Also, looks like the idle time in the shop charges the incinerator so it immediately fires once possible

**Comment by evanbowman** [comment]
I think this could be a bug with the decimator, where it won't stop firing if a fight ended when it was in the middle of a firing sequence.

**Comment by evanbowman** [comment]
61ea6031ca8d5dd3a10cbca6cad11d654d1662f0
