### ISSUE TITLE
Bug - atomics quest

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#118]
![20241203_224911](https://github.com/user-attachments/assets/b2c3c010-54a4-443c-a922-7aef8199bb47)
Encountered after accepting the atomic quest, after restarting, the save data is nuked

**Comment by Doronimmo** [comment]
Note: this is the leatest release version

**Comment by evanbowman** [comment]
Oh! That's not good at all. What's in your save file? Is it completely empty?

**Comment by Doronimmo** [comment]
> Oh! That's not good at all. What's in your save file? Is it completely empty?

Not sure, at least the adventure save is gone

**Comment by evanbowman** [comment]
do you have a copy of the save file?

**Comment by evanbowman** [comment]
Sometimes it is possible to recover data, which may be useful for reproducing the problem

**Comment by Doronimmo** [comment]
[Skyland.sav.txt](https://github.com/user-attachments/files/18009584/Skyland.sav.txt)

started another game after that, so I'm not sure if it still has the data, but I hope you will find it useful! (renamed the file to .txt format for github to support it)

**Comment by evanbowman** [comment]
> [Skyland.sav.txt](https://github.com/user-attachments/files/18009584/Skyland.sav.txt)
> 
> started another game after that, so I'm not sure if it still has the data, but I hope you will find it useful! (renamed the file to .txt format for github to support it)

Thank you! I am very busy this week, but I will try to look into it when I have some time.

**Comment by evanbowman** [comment]
Recently I've fixed two different bugs that caused problems like this when accepting quests, I don't know if I fixed this issue yet, but I fixed something at least.

**Comment by Doronimmo** [comment]
This issue seems to be extreamly rare, and probably solved by now. Closed.

**Comment by evanbowman** [comment]
I think I may have solved this and the other issue related to crashes upon accepting quests when I made a few changes to how quest destinations were calculated, although because the issue was uncommon in the first place, I was uncertain if I'd fixed it or not. That said, I haven't seen the problem in a while.
