### ISSUE TITLE
Show weapon directional icons for blocks given/sold to the player in adventure mode

### ISSUE THREAD

**Issue by evanbowman** [evanbowman/skyland-beta#12]
Construction mode shows weapon directional icons. I think I should do the same for blocks given by events.

**Comment by tolik518** [comment]
I don't know if I should open another ticket for that, but I think it also would make sense to add the arrows when you are rearanging the weapons

**Comment by evanbowman** [comment]
I think that makes sense, I'm going to try to refactor the arrow drawing code into the code that draws the red selection rectangle, and hopefully I'll display arrows everywhere.

**Comment by evanbowman** [comment]
Ok, that seems to work!
![Skyland-3](https://user-images.githubusercontent.com/11904320/227941556-bab87656-ac46-4aab-811c-706cc10587c5.png)
