### ISSUE TITLE
Bug - game keeps restarting on gpsp

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#127]
This bug is specific to the gpsp emulator, after loading the neutral event on path the game will restart.
[Skyland.srm.txt](https://github.com/user-attachments/files/18141263/Skyland.srm.txt)

**Comment by Doronimmo** [comment]
Closing issue, moral of the story, DO NOT CHANGE CORES MID-GAME.

**Comment by evanbowman** [comment]
I've seen other issues on GPSP in the past. At one point I discovered that certain things were not emulated correctly in GPSP, and thought about displaying a warning, but I'm hoping that the developer can instead fix inaccuracies in the emulator. Although I understand that this is not entirely practical, as old releases of GPSP can sit around for a long time and not be updated.

**Comment by Doronimmo** [comment]
> I've seen other issues on GPSP in the past. At one point I discovered that certain things were not emulated correctly in GPSP, and thought about displaying a warning, but I'm hoping that the developer can instead fix inaccuracies in the emulator. Although I understand that this is not entirely practical, as old releases of GPSP can sit around for a long time and not be updated.

Since GPSP is designed for very low-power hardware, it seems unlikely that those issues will ever be resolved.
