### ISSUE TITLE
Bug - rewinding at shops lets you get stuff for free

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#130]
to reproduce:
1. buy at shop
2. rewind

**Comment by Doronimmo** [comment]
Possible fix could be disabling the rewind mechanic for shops?

**Comment by evanbowman** [comment]
> Possible fix could be disabling the rewind mechanic for shops?

That's possible!
To be honest, I thought I already handled this issue, because the game clears the queue of rewind events after invoking the callback on-shop-item-sel, when the player picks an item: https://github.com/evanbowman/skyland-beta/blob/4d6e54cdf9fe0070123ccfda9125a2cf39901f35/source/skyland/scene/itemShopScene.cpp#L214

Disabling rewinding completely in shops could be an easy short term fix

**Comment by evanbowman** [comment]
```
const auto loc = APP.current_world_location();
        auto& node = APP.world_graph().nodes_[loc];
        if (node.type_ == WorldGraph::Node::Type::corrupted) {
            if (not PLATFORM.speaker().is_music_playing(
                    APP.environment().music()->c_str())) {
                PLATFORM.speaker().stream_music(
                    APP.environment().music()->c_str(), 0);
            }
+        } else if (node.type_ == WorldGraph::Node::Type::shop) {
+            APP.time_stream().enable_pushes(false);
+        }
```
This change to fadeInScene may work. When the level is a shop, disable recording time events, which also disables rewinding.

**Comment by Doronimmo** [comment]
How is the rewind diabled at challenges?

**Comment by Doronimmo** [comment]
> ```
> const auto loc = APP.current_world_location();
>         auto& node = APP.world_graph().nodes_[loc];
>         if (node.type_ == WorldGraph::Node::Type::corrupted) {
>             if (not PLATFORM.speaker().is_music_playing(
>                     APP.environment().music()->c_str())) {
>                 PLATFORM.speaker().stream_music(
>                     APP.environment().music()->c_str(), 0);
>             }
> +        } else if (node.type_ == WorldGraph::Node::Type::shop) {
> +            APP.time_stream().enable_pushes(false);
> +        }
> ```
> 
> This change to fadeInScene may work. When the level is a shop, disable recording time events, which also disables rewinding.

Maybe this could be a lisp function, similar to `powerdown_enabled`

**Comment by evanbowman** [comment]
You can't rewind in shops before as of the last release, but I haven't added anything to the lisp api yet for enabling/disabling rewinding.

**Comment by Doronimmo** [comment]
added it as a shared var in a new branch https://github.com/evanbowman/skyland-beta/tree/rewind_disable_lisp

**Comment by Doronimmo** [comment]
> added it as a shared var in a new branch https://github.com/evanbowman/skyland-beta/tree/rewind_disable_lisp

keeping it as a shared var might not be the best way data wise, but that is by far the easiest.
