### ISSUE TITLE
Flag Designer: One color `A`, other color `B`

### ISSUE THREAD

**Issue by tolik518** [evanbowman/skyland-beta#16]
Additionally, to #15 it would be neat if you could have 2 colors at once when drawing, like in most 
drawing tools with the left and right mouse buttons (mspaint, aseprite, photoshop).

You could assign the primary color to A and the secondary to B - the same binding could go for choosing the color.

**Comment by Doronimmo** [comment]
https://github.com/evanbowman/skyland-beta/releases/tag/2024.11.8.0
