### ISSUE TITLE
Cancel buying

### ISSUE THREAD

**Issue by tolik518** [evanbowman/skyland-beta#23]
When buying an item you don't always know the size of the item (at least if you aren't a pro yet).
Let me cancel the placement of a bought item since this forces the player to sell blocks if the island is fully developed.

**Comment by evanbowman** [comment]
Good point, I have to restructure a bunch of code to support canceling out of the block placement prompt, but until then, I'll see if I can display block sizes in the shop menu.

**Comment by Doronimmo** [comment]
Maybe this could be done with minimal restructuring by allowing the player to press "B" on an empty space, using the rewind mechanism to return to the previous state. (Not sure if rewind supports the build menu.)

**Comment by evanbowman** [comment]
I could have the game cancel purchasing an item if you press B over an empty space, that would work.

**Comment by evanbowman** [comment]
c2a30a509fb73bbaa45437af7ca0ee0f606595bb
