### ISSUE TITLE
World exit sometimes does not work

### ISSUE THREAD

**Issue by stanl09** [evanbowman/skyland-beta#29]
in adventure mode, the node (?) that is supposed to lead to the next world sometimes doesn’t, becoming a visited node and giving you no way of proceeding.

**Comment by evanbowman** [comment]
Oh! That’s a big problem, I’ll look into it right away!

**Comment by evanbowman** [comment]
I think I fixed it: https://github.com/evanbowman/skyland-beta/releases/tag/2024.2.13.0
