### ISSUE TITLE
After opening the glossary from start menu, closeing it, pressing R and choosing where to build, if you open start menu again, it opens to the last glossary entry you were in

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#31]
Accidentally wrote problem in title, love the game!

**Comment by evanbowman** [comment]
Thanks! This behavior appears to be something I added a long time ago. When in the construction menu, you can press start as a shortcut to jump to the glossary page for the thing that you have selected in the construction menu. Maybe it's more confusing than helpful

**Comment by Doronimmo** [comment]
Oh, that is helpful! Now I realise that this was in the tutorial🤦‍♂️
