### ISSUE TITLE
Graphical glitch mgba

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#32]
There is a purple line in start menu when using mgba.

**Comment by evanbowman** [comment]
The line doesn't appear in the version of mgba that I'm using (I have mgba version 0.11-8299-5479ab130). Do you know which version of mgba that you have installed?

**Comment by Doronimmo** [comment]
I am useing the latest mgba ps vita release, I guess its more of a problem on my side

**Comment by evanbowman** [comment]
I think I vaguely remember this happening sometimes in old versions of mgba. I think it has something to do with how mgba renders the pixelated 'mosaic' effect that I'm using to blur the background behind the start menu. As recently as a few years ago, no emulator emulated the gba mosaic effect correctly as far as I remember.
