### ISSUE TITLE
Feature request - ability to turn on and off energy consumption

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#33]
This was in previous release and was taken out later, is there any way to help test it?

**Comment by evanbowman** [comment]
Hi! Yeah, if you'd like to test it, it's configurable in the game's scripts. Are you comfortable working with command line tools? I could explain how to enable it by editing the scripts (you just need to change one variable), or I could make you a special version with the feature enabled and attach it here.

The turning on/off energy consumption was disabled for a few reasons:
1) I didn't have enough time to test it fully
2) I'm not sure if it makes the game more or less fun, I am still uncertain about whether to add it. Maybe I'm just accustomed to how the game used to be without the poweroff feature

**Comment by evanbowman** [comment]
It can also be enabled in-game with a bit of scripting. Enable developer mode in the Extras menu of the title screen. Then open the file browser, and edit the file `/flash/mods/init.lisp`, by adding this line:

![Skyland-92](https://github.com/user-attachments/assets/1e7b806d-76ad-4b3b-93dd-93c2786e7bf7)

**Comment by evanbowman** [comment]
When I get back to my computer I can send you a version with it enabled

**Comment by evanbowman** [comment]
[Skyland.gba.zip](https://github.com/user-attachments/files/17562335/Skyland.gba.zip)
Here's a version with powerdown enabled

**Comment by Doronimmo** [comment]
Thanks for the explanation!
Energy management indeed adds to the game, but an option to disable some weapons without disabling their energy consumption for example when facing reflective tiles.

**Comment by evanbowman** [comment]
I added energy management back in this version https://github.com/evanbowman/skyland-beta/releases/tag/2024.10.30.0
