### ISSUE TITLE
A bug in delivery quests

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#35]
Sometimes, the quest is at the end of a zone, sometimes makeing the destination unreachable since its already in the storm.

**Comment by evanbowman** [comment]
I'll work on this! The logic for placing a destination is a bit oversimplified right now and sometimes makes a mistake about whether a location is reachable. I have a solution but I'm still testing it.

**Comment by evanbowman** [comment]
I think I've fixed it in this version https://github.com/evanbowman/skyland-beta/releases/tag/2024.10.30.0
Hopefully...
I need to continue testing to make sure it works in a bunch of different scenarios.

**Comment by Doronimmo** [comment]
> I think I've fixed it in this version https://github.com/evanbowman/skyland-beta/releases/tag/2024.10.30.0 Hopefully... I need to continue testing to make sure it works in a bunch of different scenarios.

Was given a delivery quest (masonry selling) at the end of zone 1, the destination was reachable, but only with a radar, and even with a radar you would not reach the exit in time.

**Comment by evanbowman** [comment]
> > I think I've fixed it in this version https://github.com/evanbowman/skyland-beta/releases/tag/2024.10.30.0 Hopefully... I need to continue testing to make sure it works in a bunch of different scenarios.
> 
> Was given a delivery quest (masonry selling) at the end of zone 1, the destination was reachable, but only with a radar, and even with a radar you would not reach the exit in time.

Oh! I forgot to include whether the exit was reachable in the calculations 🤦

**Comment by Doronimmo** [comment]
I think this is solved now, closing.
