### ISSUE TITLE
Problem when changeing game version in challenges

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#36]
Challenges and their respective achievements (dynamite) are not saved in the games save file somehow, which results in challenge completion being reset after updating the game not via the link cable option (changing the ROM and keeping the save)

**Comment by evanbowman** [comment]
Oops! That's not supposed to happen. I've been using the same save file for a few years and I haven't lost anything, so I'm surprised, I'll try it with a fresh save and see if I can get it to happen.

**Comment by Doronimmo** [comment]
I cannot recreate this cenario with current or previous version, so it's probably not a problem, I guess it has something to do with the version my save was originally created on.
