### ISSUE TITLE
Bug in select menu when hovering over enemy crewmembers

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#39]
When hovering over enemy crewmembers and pressing select there is an option to pin crewmember and to change crewmember icon.

**Comment by evanbowman** [comment]
Oh! That's a pretty big mistake on my part. Fortunately it seems that the option to pin enemy crew to a location doesn't do anything

**Comment by evanbowman** [comment]
At the rate that your finding bugs, I'm gonna have to put you in the credits before long https://github.com/evanbowman/skyland-beta/blob/master/scripts/data/credits/7.txt

**Comment by evanbowman** [comment]
Fixed here: https://github.com/evanbowman/skyland-beta/releases
