### ISSUE TITLE
ENHANCEMENT - balance divert power

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#41]
The divert power option makes the early game easier, but it could make the game more approachable for newcomers trying to test different stuff, so maybe it could be an easy mode exclusive with hard/medium modes still having the ability to stop a weapon from fireing but still consuming energy.

**Comment by evanbowman** [comment]
Interesting idea, I'll try making those changes and see how it looks!

**Comment by evanbowman** [comment]
https://github.com/evanbowman/skyland-beta/releases/tag/2024.10.31.2
