### ISSUE TITLE
Enhancement - Command queueing

### ISSUE THREAD

**Issue by evanbowman** [evanbowman/skyland-beta#44]
I'm going to consider the possibility of adding command queuing throughout the game. E.g. so that you can hold down a button when selecting a weapon target to instead select a sequence of targets, such that we weapon (or group of weapons) will continue on to the next target after finishing the current one.

**Comment by evanbowman** [comment]
I created an initial draft of this. I'm thinking of adding numbered target icons to make it easier to see the ordering of targets in the queue. And I'll need to add target queueing for drones.

**Comment by Doronimmo** [comment]
maybe the queue could show in the minimap when hovering over the weapon group.

**Comment by evanbowman** [comment]
> maybe the queue could show in the minimap when hovering over the weapon group.

I think that's a good idea. I display the targets over the enemy castle itself when hovering over a weapon, but of course on large levels this ends up being offscreen

**Comment by evanbowman** [comment]
I don't remember which release it was, but I do show command queue selections in the minimap now. I'm going to close this issue, and create a new issue in the future for any further enhancements related to command queueing.
