### ISSUE TITLE
Arrows when building drone bay/solar panel

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#48]
Since these won't work when blocked from above, it could show arrows similar to when building weapons

**Comment by evanbowman** [comment]
Good idea! Currently the game only displays arrows for things categorized as weapons, but I could do it for other types of stuff

**Comment by evanbowman** [comment]
I added an arrow to drone-bays. I have to check whether solar-panels are affected by blocks placed on top of them, they might only be affected by weather.

**Comment by evanbowman** [comment]
solar panels are unaffected by blocks placed on top of them, so I won't add any arrows for now. Solar panels are only affected by the weather. I'm closing the issue for now as I completed the other changes for drone bays.
