### ISSUE TITLE
Bug - replicants won't heal

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#49]
When a new replicant goes to the infirmary with 19 HP he will not heal to 25, instead staying at 19

**Comment by evanbowman** [comment]
I'll need to help explain this better in the game, replicants intentionally can't heal. The replicator tutorial isn't very good, I'll add some dialog to it.

The glossary does explain replicant health on the replicator page, though

**Comment by evanbowman** [comment]
Given the relatively cheap cost of replicants, I think they would be overpowered if you could heal them

**Comment by Doronimmo** [comment]
So maybe they would not show 25 hp max? This would make it more logical

**Comment by evanbowman** [comment]
Ah! Good idea! Let me see how easy that would be to change

**Comment by evanbowman** [comment]
Max hp fixed: https://github.com/evanbowman/skyland-beta/releases/tag/2024.11.1.3
