### ISSUE TITLE
Fire is retaind throughout challenges

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#50]
When catching fire in fire bridge challenge, the quiting and opening the mycelium challenge, the fire will appear in the same places

**Comment by evanbowman** [comment]
Oops! That is likely to make the mycelium challenge significantly easier lol

**Comment by Doronimmo** [comment]
![20241101_132507](https://github.com/user-attachments/assets/899043ed-9231-4eb8-b890-41eccbdb1156)
![20241101_132430](https://github.com/user-attachments/assets/89acc942-f361-4d66-a199-931b556567f6)

**Comment by Doronimmo** [comment]
This problem happens on all challenges

**Comment by evanbowman** [comment]
Fixed: https://github.com/evanbowman/skyland-beta/releases/tag/2024.11.1.3
