### ISSUE TITLE
Game freezes after quitting challenge

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#51]
After quitting goliath game will freeze and occasionally play a sound
![20241101_133037](https://github.com/user-attachments/assets/472b5278-e479-46a3-a27f-d94eac3ec1a6)

**Comment by evanbowman** [comment]
I'm unable to reproduce this issue myself, unfortunately. If this problem happens consistently for you, do you know if there's anything you do in particular after starting the level, but before quitting?

**Comment by Doronimmo** [comment]
> I'm unable to reproduce this issue myself, unfortunately. If this problem happens consistently for you, do you know if there's anything you do in particular after starting the level, but before quitting?

I think that I waited an extraordinary amount of time doing nothing in this challenge (1 hr or so in fast forward so maybe 3-2 hours in-game)

**Comment by Doronimmo** [comment]
Cannot reproduce issue, closing
