### ISSUE TITLE
Crash on pressing retry after losing 

### ISSUE THREAD

**Issue by tolik518** [evanbowman/skyland-beta#6]
So I was playing in adventure mode on easy and ws losing this fight against a pirate ship (on second stage) and when I was promted to retry the game crashed for me.

![Fatal error makes sad](https://user-images.githubusercontent.com/3026792/226903813-a9dcdbcb-0af2-4ca8-af4a-10a2d7de4c08.jpg)

Bressing B have sadly not worked. So I had to restart the game - and was able to recover the save game :) 

Is there a way to get a more verbose error next time to be able to share it?

**Comment by evanbowman** [comment]
Thanks for reporting this! Yeah for fatal errors, the game keeps a backup save in memory and writes it upon crashes, so you're able to recover. This particular error is pretty unusual, I will have to add some more verbose logging.

I know where in the code the issue happened, based on the error message https://github.com/evanbowman/skyland-beta/blob/master/source/skyland/scene/rewindScene.cpp#L1056. I just need to do some testing to figure out how the game could end up in this state.

Cool gameboy!

**Comment by evanbowman** [comment]
At the very least, I can give players the option to retry the level from the beginning if an error like this occurs during rewinding.

**Comment by evanbowman** [comment]
Ok! Until I can figure out what went wrong, I created a patch to allow you to retry a level upon fatal errors without restarting the game.

**Comment by tolik518** [comment]
Thanks a lot for looking into it and for fixit it so fast! 

I love the game a lot so far - I'm have followed the development for some months now and I was wondering if it's ok to open tickets for feature requests or potential improvements?

**Comment by evanbowman** [comment]
Yes of course! I encourage you to do so; any feedback you have could be useful to me for improving the game.

**Comment by tolik518** [comment]
Thank you, I will open some tickets in the following days :)

**Comment by evanbowman** [comment]
I've made so many changes since this issue was created, that I'm unsure if it's worth trying to reproduce this issue again. I'm cleaning up old issues and I'm going to close this one, as I haven't been able to reproduce the problem for a long time and I may have unknowingly fixed it at some point.
