### ISSUE TITLE
Bug - quitting the loading screen early

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#65]
![title](https://github.com/user-attachments/assets/c5fc8f6e-a008-4aac-b3fe-f5f347c6f702)
When seeing this screen, you can press B to exit to main menu, but it will lag until loading is finished

**Comment by evanbowman** [comment]
The game isn't actually lagging or loading anything, there's a 400 millisecond pause as part of the intro sequence that's not being skipped when pressing B. I can fix it.

**Comment by evanbowman** [comment]
https://github.com/evanbowman/skyland-beta/commit/2fa4fa4708f35ab284bbe572ca9f0a7b21ef7698#diff-2a39879e0c9a041716f6ee3254054fd61ef62c3851fed729e7d8a1f5f1582b05R165-R168
I added a commit to fix it, I'll include this next time I do a release
