### ISSUE TITLE
Goblin recruit icon

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#70]
![character_art](https://github.com/user-attachments/assets/726639a6-4646-4ae2-88fb-3786b71018e7)
There is character art for a goblin crewmember, but it is not in the change character icon option in the SELECT menu

**Comment by evanbowman** [comment]
Originally I was going to give every crew member that you recruite in the game an icon, and the goblin crewmember icon was for goblins that came aboard when surrendering. It's not currently used for anything, but I could easily add it to the list of character icons in the select menu.

**Comment by evanbowman** [comment]
Completed
