### ISSUE TITLE
FATAL ERROR in FATAL ERROR

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#71]
welp, I am out of words
![ERROR](https://github.com/user-attachments/assets/5abe2988-dd80-45cd-a2f7-164497af9891)

**Comment by Doronimmo** [comment]
[game.zip](https://github.com/user-attachments/files/17621985/game.zip)
this is the .gba that I was using (custom) and save file + state for mgba

**Comment by Doronimmo** [comment]
NOTE:
I realized that I did not explain what I did that coused the issue, I opened challenge no. 14 - bop badop

**Comment by evanbowman** [comment]
Hi! The regression program might be helpful for things like this!
![Skyland-0](https://github.com/user-attachments/assets/01d0097f-cddd-41da-a2cb-682224fe5359)

It looks like you're referencing <challenge_id>, a variable that does not exist

**Comment by Doronimmo** [comment]
> Hi! The regression program might be helpful for things like this! ![Skyland-0](https://private-user-images.githubusercontent.com/11904320/382865462-01d0097f-cddd-41da-a2cb-682224fe5359.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NDMwMDIsIm5iZiI6MTczMDc0MjcwMiwicGF0aCI6Ii8xMTkwNDMyMC8zODI4NjU0NjItMDFkMDA5N2YtY2RkZC00MWRhLWEyY2ItNjgyMjI0ZmU1MzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDE3NTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlN2ExMGM2NDQ4ZjY0Mjc3NGIxZTlkZDI2NzBhY2VkNWZlZDc4YTRkMDgyZWFmYjBjNmU4NDI4NWQ2MTA5OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SuCR55OjiWqDvInBLFMMHWaxF5LpwfmBQpXbgoJGlpM)
> 
> It looks like you're referencing <challenge_id>, a variable that does not exist

just ran regression myself, fixed the problem, the artifacts were probably from screenshake when error happend

**Comment by evanbowman** [comment]
By the way, when making levels, you can use the sandbox to help you. When developer mode is enabled, the game saves sandbox levels with compression turned off, so you can go into the Skyland.sav file and copy the level layouts into your script

**Comment by evanbowman** [comment]
For example, I turned on developer mode, made a level in the sandbox, and saved it. Then, opening up the game's save file:
```/save/sb0.lisp'((save-protocol . 3) (rooms ((power-core 1 13) (drone-bay 1 12 160) (hull 2 11 150) (hull 3 14) (hull 3 10) (hull 3 11 40) (hull 3 13 160) (hull 3 12 80)) (cannon 0 14) (cannon 0 13) (cannon 0 12) (cannon 0 11) (hull 0 10) (power-core 1 13) (reactor 3 12) (missile-silo 3 10)) (chrs ((2 14 (id . 1)) (1 14 (id . 2))) (3 14 (id . 4)) (4 14 (id . 3))) (groups (Up) (Left) (Right) (poweroff)) (weather . 1) (terrain 4 . 5))```

**Comment by Doronimmo** [comment]
> By the way, when making levels, you can use the sandbox to help you. When developer mode is enabled, the game saves sandbox levels with compression turned off, so you can go into the Skyland.sav file and copy the level layouts into your script

this was the artifact of trying to automate sandbox save to challenge data 🙃

**Comment by evanbowman** [comment]
Ah! Makes sense!

You're right, though, there is an issue. I'll keep this issue open and try to figure out what broke the fatal error screen! Eventually... I can't look until later.

**Comment by Doronimmo** [comment]
for future referance - this is the structure for sandbox saves:

(list
 (cons 'save-protocol 3)
 (cons 'rooms (cons (rooms (player)) (rooms (opponent))))
 (cons 'chrs (cons (chrs (player)) (chrs (opponent))))
 (cons 'groups (groups))
 (cons 'weather (weather))
 (cons 'terrain (cons (terrain (player)) (terrain (opponent)))))

**Comment by evanbowman** [comment]
It seems that this is not actually a fatal error occurring during a fatal error. The radial explosion effect when a castle explodes requires per-scanline raster effects. In the middle of the explosion sequence, the engine calls the lisp function on-victory, which raises a fatal error, but the raster effect created for the circular explosion graphics is still running with junk data, causing random scanlines to disappear.
