### ISSUE TITLE
player buildings are invisible in FOREVER

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#72]
![bug in forever](https://github.com/user-attachments/assets/f6b1489e-97c4-4bd2-8733-18d0cc039ec1)

**Comment by Doronimmo** [comment]
also, is the number up to the weather?

**Comment by evanbowman** [comment]
Oh! I must have broken this recently. I also need to replace the weather numbers with text, I'll work on it.

**Comment by evanbowman** [comment]
Ah! The changes I made recently to put out fires on challenge levels broke rendering elsewhere

**Comment by evanbowman** [comment]
I fixed both of these things in the latest release, thanks for bringing it to my attention that this stuff was broken
