### ISSUE TITLE
Weapon states are saved in rewind

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#75]
Charged my decimator, it started shooting and then I rewinded, after the rewind the decimator instantly shot

**Comment by Doronimmo** [comment]
You can also spam the decimator via charging it, waiting for it to start shooting, and rewind- infinite destruction

**Comment by evanbowman** [comment]
Thanks for reminding me, I was meaning to fix that

**Comment by evanbowman** [comment]
https://github.com/evanbowman/skyland-beta/releases/tag/2024.11.6.0
