### ISSUE TITLE
unpack_sav.py will not decompress

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#76]
switched to using [heatshrink2](https://pypi.org/project/heatshrink2/) since could not import the normal one, code runs without errors but some of the files are still compressed.
currently using an .sh script with command line instead, but some files will still be compressed.
included the extracted_cart_ram folder with compressed+decompressed files.

[extracted_cart_ram.zip](https://github.com/user-attachments/files/17690340/extracted_cart_ram.zip)

**Comment by evanbowman** [comment]
I didn't know about heatshrink2! The original heatshrink package seems to only be compatible with the old version of the python interpreter. I imported heatshrink2 instead and fixed a bug in one part of the script.
https://github.com/evanbowman/skyland-beta/blob/master/tools/unpack_sav.py

**Comment by Doronimmo** [comment]
Thanks! the script works flawlessly, the new folder structure is very helpful!
 Probably a problem on my side but the `global.dat` and `adventure.dat` are full of null, I dont really know what should be in these files so its probably fine, other then that this issue is ready to be closed.

**Comment by evanbowman** [comment]
It's not quite perfect, but it works well enough. Due to a minor mistake, the unpack_sav script extracts deleted files from the save memory filesystem (e.g. the test.dat file created and then deleted by regression in apitest.lisp). Maybe I'll fix it someday, but I'm labeling the issue as closed for now.

**Comment by evanbowman** [comment]
When running the script, you may see unpack_sav extract a file multiple times. These are older revisions of the file in save ram, it's just a sideffect of how flash chips work, I'm not planning on fixing this either, as the last extracted version of the file will just overwrite the previously extracted one.
