### ISSUE TITLE
some things will flicker when changeing palettes

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#79]
![color change](https://github.com/user-attachments/assets/6960bb97-02ac-4620-b044-12b470698968)

**Comment by evanbowman** [comment]
Oh! That doesn't happen for me, which emulator and emulator version are you using?

**Comment by evanbowman** [comment]
Does the color flicker happen throughout the game, or just when using the palette changing options?

**Comment by Doronimmo** [comment]
> Does the color flicker happen throughout the game, or just when using the palette changing options?

just when changeing palettes

**Comment by evanbowman** [comment]
I downloaded that version and tried it, I'm having trouble reproducing the issue, is there anything that you do before changing color settings? Or just go to the title screen, scroll right, and pick the color profiles option?

**Comment by Doronimmo** [comment]
> I downloaded that version and tried it, I'm having trouble reproducing the issue, is there anything that you do before changing color settings? Or just go to the title screen, scroll right, and pick the color profiles option?

this seems to be a problem with github uploads, because I can't reproduce the issue and the record gif seems fine.

NOTE: added the gif in zip so github will not cause it any harm
[color change.zip](https://github.com/user-attachments/files/17751370/color.change.zip)

**Comment by Doronimmo** [comment]
github seems to paint the black parts white, and this causes the flicker, but the flicker is still there, just less noticeable.

**Comment by Doronimmo** [comment]
this seems to change based on frameskip, and the avrage user will probably never notice this, closing.
