### ISSUE TITLE
Show the Shooting Direction

### ISSUE THREAD

**Issue by tolik518** [evanbowman/skyland-beta#8]
When in building mode it would be nice to see the shooting direction of the block or the direction in which it needs free space to work correctly. An idea would be to show an arrow on/above the block.

![skyland](https://user-images.githubusercontent.com/3026792/227714824-2cfdbbc4-81b7-4c63-8e7a-e699f91354ab.png)

Not knowing in which direction the block shoots was the main reason for me not wanting to try new weapons.

**Comment by evanbowman** [comment]
Great idea! I can easily add this!

**Comment by evanbowman** [comment]
I've added this to the latest release: https://github.com/evanbowman/skyland-beta/releases/tag/2023.3.25.0
I still need to add the arrows for events that give/sell you blocks. I will address this in a separate issue.
