### ISSUE TITLE
ENHANCEMENT - add portals

### ISSUE THREAD

**Issue by evanbowman** [evanbowman/skyland-beta#80]
**Is your feature request related to a problem? Please describe.**
No

**Describe wanted behaviour**
Portals require a manufactory and consume some power. They link disconnected areas of your castle.
![ezgif-1-15a3e7efc0](https://github.com/user-attachments/assets/042d0cb0-d073-49d5-b429-2fad33a38d71)

**Describe alternatives you've considered**
Ladders/stairwells exist, but I'm testing out portals and they're pretty fun.

**Additional pictures**
N/A

**Comment by Doronimmo** [comment]
Looking through the commits, it appears that the portal would cost 800 coins? (I don't think in game currency has a name) that seems cheap + only one block seems kind of overpowered.

**Comment by evanbowman** [comment]
> Looking through the commits, it appears that the portal would cost 800 coins? (I don't think in game currency has a name) that seems cheap + only one block seems kind of overpowered.

Yeah, I just started working on it today, it'll need some more adjustment

**Comment by evanbowman** [comment]
I wonder... should fire spread through portals?
