### ISSUE TITLE
Projectiles are saved between levels

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#85]
Similar to #50

**Comment by Doronimmo** [comment]
Fixed? 41ff599

**Comment by evanbowman** [comment]
> Fixed? [41ff599](https://github.com/evanbowman/skyland-beta/commit/41ff599f8e09487d8bd17cdc214ab525eabbd255)

I'm not certain if this fixes it, because I haven't seen the issue happen myself. But this code change erases all projectiles when loading any level, so hopefully I've finally fixed it.
