### ISSUE TITLE
"Lonely castaway"-island when there is no room

### ISSUE THREAD

**Issue by tolik518** [evanbowman/skyland-beta#9]
There are some island where you can get new crew member, the one with the "Lonely castaway" is an example of that.
If you don't have enough room on your island then you simply get a prompt where it says there is no room and the scene ends.

It would be nice to get a prompt with the question if one wants to build a new room and be asked again.

**Comment by evanbowman** [comment]
Yeah this is possible, I'll try to get to it soon! Actually, for another similar event where you pickup a crewmember, I scripted an event where you get a chance to create space for new people: https://github.com/evanbowman/skyland-beta/blob/2952dea82eca82e2734242f8af1613471cbfd43e/scripts/event/neutral/0/5.lisp#L59
