### ISSUE TITLE
ENHANCEMENT - stats for crew members

### ISSUE THREAD

**Issue by evanbowman** [evanbowman/skyland-beta#90]
I think it would be fun to add cumulative stats for crew members. For example, you'd be able to select a crew member and see stats like: damage repaired, damage caused, goblins killed, battles fought in, etc. 

Challenges:
1) There's not enough memory in crew objects to fit all of these stats
2) Be careful during rewinding to reverse stat changes correctly

**Comment by evanbowman** [comment]
For now I've decided to add three stats:
1) battles participated in
2) goblins defeated
3) blocks repaired

Future work:
Some other stats, like distance travelled, idle time, etc. might be fun, but I'll have to think about where they would be displayed in the UI.
These stats could also be fun to see upon completing a game. Create a new menu for this? Or just put the info into the adventure log?

**Comment by Doronimmo** [comment]
> For now I've decided to add three stats:
> 
> 1. battles participated in
> 2. goblins defeated
> 3. blocks repaired
> 
> Future work: Some other stats, like distance travelled, idle time, etc. might be fun, but I'll have to think about where they would be displayed in the UI. These stats could also be fun to see upon completing a game. Create a new menu for this? Or just put the info into the adventure log?

maybe these stats could show at game over/win screen (I dont really know well how that screen looks since I dont really win that much)
